---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: employee-poc-deployment
spec:
  replicas: 4
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app: employeepoc
      version: v01
  template:
    metadata:
      labels:
        app: employeepoc
        version: v01
    spec:
      containers:
      - name: employeepoc-container
        image: nikumari/employeepoc:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080


